# shared/protocol.py

# JSON Keys
FIELD_COMMAND = "command"
FIELD_PAYLOAD = "payload"
FIELD_STATUS = "status"
FIELD_MESSAGE = "message"
FIELD_TOKEN = "token"

# Status Codes
STATUS_OK = "OK"
STATUS_ERROR = "ERROR"

# Developer Commands
CMD_DEV_REGISTER = "DEV_REGISTER"
CMD_DEV_LOGIN = "DEV_LOGIN"
CMD_GAME_UPLOAD = "GAME_UPLOAD"
CMD_GAME_LIST_MY = "GAME_LIST_MY"
CMD_GAME_UPDATE = "GAME_UPDATE"
CMD_GAME_DELETE = "GAME_DELETE"

# Player Commands
CMD_PLAYER_REGISTER = "PLAYER_REGISTER"
CMD_PLAYER_LOGIN = "PLAYER_LOGIN"
CMD_STORE_LIST = "STORE_LIST"
CMD_GAME_DETAIL = "GAME_DETAIL"
CMD_GAME_DOWNLOAD = "GAME_DOWNLOAD"
CMD_PLAYER_LIST = "PLAYER_LIST"
CMD_ROOM_CREATE = "ROOM_CREATE"
CMD_ROOM_LIST = "ROOM_LIST"
CMD_ROOM_JOIN = "ROOM_JOIN"
CMD_GAME_START_NOTIFY = "GAME_START_NOTIFY" # Server -> Client (Host) to start game
CMD_GAME_RATING = "GAME_RATING"
